# Site settings
title: Justen Cate's Data Analyst Portfolio
author:
  name: Justen Cate
  email: justencate@gmail.com
description: "Data detective on a mission! ğŸ” Turning numbers into narratives. Passionate about finding patterns 
              and driving decisions through data storytelling."

# Build settings
theme: jekyll-theme-minimal
